spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/angularteste
    password: 'tt333'
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'

